# Generated by Django 4.2.5 on 2023-09-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('email', 'username')},
        ),
    ]
