# Generated by Django 4.2.5 on 2023-10-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_remove_memory_album_remove_memory_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='memories',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='title',
        ),
        migrations.AddField(
            model_name='memory',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='memories', to='memories.album'),
        ),
        migrations.AlterField(
            model_name='album',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
    ]
