# Generated by Django 4.2.5 on 2023-10-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_remove_album_memories_remove_memory_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='albums',
        ),
        migrations.AddField(
            model_name='memory',
            name='album',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='memories.album'),
        ),
    ]
